### ISSUE TITLE
ImportError: DLL failed to load:% 1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by cnrting** [amol9/imagebot#2]
D:\>imagebot crawl http://www.bbc.com -m -s 640x480 -l info -is "E:\Photos\BBC"
2017-06-04 19:32:30 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: imagebot)
2017-06-04 19:32:30 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'imagebot.spiders', 'LOG_LEVEL': 20, 'SPIDER_MODULES': ['imagebot.spiders'], 'HTTPCACHE_ENABLED': True, 'BOT_NAME': 'imagebot', 'USER_AGENT': 'imagebot', 'HTTPCACHE_DIR': 'C:\\Users\\CP\\.imagebot\\httpcache', 'HTTPCACHE_POLICY': 'scrapy.extensions.httpcache.RFC2616Policy'}
2017-06-04 19:32:30 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-06-04 19:32:30 [root] ERROR: No module named gi
Unhandled error in Deferred:
2017-06-04 19:32:30 [twisted] CRITICAL: Unhandled error in Deferred:

2017-06-04 19:32:30 [twisted] CRITICAL:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\twisted\internet\defer.py", line 1301, in _inlineCallbacks
    result = g.send(result)
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\crawler.py", line 95, in crawl
    six.reraise(*exc_info)
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\crawler.py", line 77, in crawl
    self.engine = self._create_engine()
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\crawler.py", line 102, in _create_engine
    return ExecutionEngine(self, lambda _: self.stop())
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\core\engine.py", line 69, in __init__
    self.downloader = downloader_cls(crawler)
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\core\downloader\__init__.py", line 88, in __init__
    self.middleware = DownloaderMiddlewareManager.from_crawler(crawler)
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\middleware.py", line 58, in from_crawler
    return cls.from_settings(crawler.settings, crawler)
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\middleware.py", line 34, in from_settings
    mwcls = load_object(clspath)
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\utils\misc.py", line 44, in load_object
    mod = import_module(module)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\python27\lib\site-packages\scrapy-1.4.0-py2.7.egg\scrapy\downloadermiddlewares\retry.py", line 20, in <module>
    from twisted.web.client import ResponseFailed
  File "c:\python27\lib\site-packages\twisted\web\client.py", line 42, in <module>
    from twisted.internet.endpoints import HostnameEndpoint, wrapClientTLS
  File "c:\python27\lib\site-packages\twisted\internet\endpoints.py", line 37, in <module>
    from twisted.internet.stdio import StandardIO, PipeAddress
  File "c:\python27\lib\site-packages\twisted\internet\stdio.py", line 30, in <module>
    from twisted.internet import _win32stdio
  File "c:\python27\lib\site-packages\twisted\internet\_win32stdio.py", line 9, in <module>
    import win32api
ImportError: DLL failed to load:% 1 is not a valid Win32 application.

**Comment by amol9** [comment]
Looks like you need to install pywin32.
